eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    lease-expiration-duration-in-seconds: 2
server:
  port: 8761
spring:
  application:
    name: eureka

  zipkin:
    enabled: true
    base-url: http://localhost:9411/